### ISSUE TITLE
from werkzeug.wsgi import DispatcherMiddleware

### ISSUE THREAD

**Issue by cicihou** [pilosus/flask_prometheus_metrics#35]
Werkzeug                 0.14.1   
Python                      3.6
MacOS
Pycharm

`from werkzeug.middleware.dispatcher import DispatcherMiddleware `
not work

`from werkzeug.wsgi import DispatcherMiddleware`
work

**Comment by pilosus** [comment]
You are right. It's been moved in `werkzeug 0.15.0`, see [changelog](http://werkzeug.palletsprojects.com/en/0.15.x/changes/?highlight=dispatchermiddleware#version-0-15-0).
I don't think it's worth mentioning in README's minimal working example to keep it short and concise. But I will label this issue so that other people could find it. Thanks
